//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("HR_DeptModel", "FK__Employee__dept_c__060DEAE8", "Department", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(THE_PROJECT_E_PERSONAL.DataAcc.Department), "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(THE_PROJECT_E_PERSONAL.DataAcc.Employee), true)]

#endregion

namespace THE_PROJECT_E_PERSONAL.DataAcc
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HR_DeptEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HR_DeptEntities object using the connection string found in the 'HR_DeptEntities' section of the application configuration file.
        /// </summary>
        public HR_DeptEntities() : base("name=HR_DeptEntities", "HR_DeptEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HR_DeptEntities object.
        /// </summary>
        public HR_DeptEntities(string connectionString) : base(connectionString, "HR_DeptEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HR_DeptEntities object.
        /// </summary>
        public HR_DeptEntities(EntityConnection connection) : base(connection, "HR_DeptEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Department> Departments
        {
            get
            {
                if ((_Departments == null))
                {
                    _Departments = base.CreateObjectSet<Department>("Departments");
                }
                return _Departments;
            }
        }
        private ObjectSet<Department> _Departments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employees
        {
            get
            {
                if ((_Employees == null))
                {
                    _Employees = base.CreateObjectSet<Employee>("Employees");
                }
                return _Employees;
            }
        }
        private ObjectSet<Employee> _Employees;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Departments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDepartments(Department department)
        {
            base.AddObject("Departments", department);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="emp_code">No Metadata Documentation available.</param>
        public ObjectResult<sp_search_emp_Result> sp_search_emp(Nullable<global::System.Int32> emp_code)
        {
            ObjectParameter emp_codeParameter;
            if (emp_code.HasValue)
            {
                emp_codeParameter = new ObjectParameter("emp_code", emp_code);
            }
            else
            {
                emp_codeParameter = new ObjectParameter("emp_code", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<sp_search_emp_Result>("sp_search_emp", emp_codeParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HR_DeptModel", Name="Department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Department : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Department object.
        /// </summary>
        /// <param name="dept_code">Initial value of the dept_code property.</param>
        public static Department CreateDepartment(global::System.Int32 dept_code)
        {
            Department department = new Department();
            department.dept_code = dept_code;
            return department;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 dept_code
        {
            get
            {
                return _dept_code;
            }
            set
            {
                if (_dept_code != value)
                {
                    Ondept_codeChanging(value);
                    ReportPropertyChanging("dept_code");
                    _dept_code = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("dept_code");
                    Ondept_codeChanged();
                }
            }
        }
        private global::System.Int32 _dept_code;
        partial void Ondept_codeChanging(global::System.Int32 value);
        partial void Ondept_codeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dept_name
        {
            get
            {
                return _dept_name;
            }
            set
            {
                Ondept_nameChanging(value);
                ReportPropertyChanging("dept_name");
                _dept_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dept_name");
                Ondept_nameChanged();
            }
        }
        private global::System.String _dept_name;
        partial void Ondept_nameChanging(global::System.String value);
        partial void Ondept_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dept_location
        {
            get
            {
                return _dept_location;
            }
            set
            {
                Ondept_locationChanging(value);
                ReportPropertyChanging("dept_location");
                _dept_location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dept_location");
                Ondept_locationChanged();
            }
        }
        private global::System.String _dept_location;
        partial void Ondept_locationChanging(global::System.String value);
        partial void Ondept_locationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HR_DeptModel", "FK__Employee__dept_c__060DEAE8", "Employee")]
        public EntityCollection<Employee> Employees
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Employee>("HR_DeptModel.FK__Employee__dept_c__060DEAE8", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Employee>("HR_DeptModel.FK__Employee__dept_c__060DEAE8", "Employee", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HR_DeptModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="emp_code">Initial value of the emp_code property.</param>
        public static Employee CreateEmployee(global::System.Int32 emp_code)
        {
            Employee employee = new Employee();
            employee.emp_code = emp_code;
            return employee;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 emp_code
        {
            get
            {
                return _emp_code;
            }
            set
            {
                if (_emp_code != value)
                {
                    Onemp_codeChanging(value);
                    ReportPropertyChanging("emp_code");
                    _emp_code = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("emp_code");
                    Onemp_codeChanged();
                }
            }
        }
        private global::System.Int32 _emp_code;
        partial void Onemp_codeChanging(global::System.Int32 value);
        partial void Onemp_codeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String emp_name
        {
            get
            {
                return _emp_name;
            }
            set
            {
                Onemp_nameChanging(value);
                ReportPropertyChanging("emp_name");
                _emp_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("emp_name");
                Onemp_nameChanged();
            }
        }
        private global::System.String _emp_name;
        partial void Onemp_nameChanging(global::System.String value);
        partial void Onemp_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String emp_designation
        {
            get
            {
                return _emp_designation;
            }
            set
            {
                Onemp_designationChanging(value);
                ReportPropertyChanging("emp_designation");
                _emp_designation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("emp_designation");
                Onemp_designationChanged();
            }
        }
        private global::System.String _emp_designation;
        partial void Onemp_designationChanging(global::System.String value);
        partial void Onemp_designationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> emp_date_appointed
        {
            get
            {
                return _emp_date_appointed;
            }
            set
            {
                Onemp_date_appointedChanging(value);
                ReportPropertyChanging("emp_date_appointed");
                _emp_date_appointed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("emp_date_appointed");
                Onemp_date_appointedChanged();
            }
        }
        private Nullable<global::System.Int32> _emp_date_appointed;
        partial void Onemp_date_appointedChanging(Nullable<global::System.Int32> value);
        partial void Onemp_date_appointedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dept_code
        {
            get
            {
                return _dept_code;
            }
            set
            {
                Ondept_codeChanging(value);
                ReportPropertyChanging("dept_code");
                _dept_code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dept_code");
                Ondept_codeChanged();
            }
        }
        private Nullable<global::System.Int32> _dept_code;
        partial void Ondept_codeChanging(Nullable<global::System.Int32> value);
        partial void Ondept_codeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HR_DeptModel", "FK__Employee__dept_c__060DEAE8", "Department")]
        public Department Department
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("HR_DeptModel.FK__Employee__dept_c__060DEAE8", "Department").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("HR_DeptModel.FK__Employee__dept_c__060DEAE8", "Department").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Department> DepartmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("HR_DeptModel.FK__Employee__dept_c__060DEAE8", "Department");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Department>("HR_DeptModel.FK__Employee__dept_c__060DEAE8", "Department", value);
                }
            }
        }

        #endregion
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="HR_DeptModel", Name="sp_search_emp_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class sp_search_emp_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String emp_name
        {
            get
            {
                return _emp_name;
            }
            set
            {
                Onemp_nameChanging(value);
                ReportPropertyChanging("emp_name");
                _emp_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("emp_name");
                Onemp_nameChanged();
            }
        }
        private global::System.String _emp_name;
        partial void Onemp_nameChanging(global::System.String value);
        partial void Onemp_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String emp_designation
        {
            get
            {
                return _emp_designation;
            }
            set
            {
                Onemp_designationChanging(value);
                ReportPropertyChanging("emp_designation");
                _emp_designation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("emp_designation");
                Onemp_designationChanged();
            }
        }
        private global::System.String _emp_designation;
        partial void Onemp_designationChanging(global::System.String value);
        partial void Onemp_designationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dept_name
        {
            get
            {
                return _dept_name;
            }
            set
            {
                Ondept_nameChanging(value);
                ReportPropertyChanging("dept_name");
                _dept_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dept_name");
                Ondept_nameChanged();
            }
        }
        private global::System.String _dept_name;
        partial void Ondept_nameChanging(global::System.String value);
        partial void Ondept_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Years_of_service
        {
            get
            {
                return _Years_of_service;
            }
            set
            {
                OnYears_of_serviceChanging(value);
                ReportPropertyChanging("Years_of_service");
                _Years_of_service = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Years_of_service");
                OnYears_of_serviceChanged();
            }
        }
        private Nullable<global::System.Int32> _Years_of_service;
        partial void OnYears_of_serviceChanging(Nullable<global::System.Int32> value);
        partial void OnYears_of_serviceChanged();

        #endregion
    }

    #endregion
    
}
